### ISSUE TITLE
Missing some Sensors

### ISSUE THREAD

**Issue by FrankTodoque** [IamTheCarl/system-mqtt#10]
Hi Carl - 
first of all, thanks for the great tool.

Do you have any idea why only CPU usage and Memory usage, but not Swap usage, Filesystem usage, Battery state and Battery level are visible in Broker?
My environment: Linux Mint / HA in VMware.

Thanks in advance.

**Comment by IamTheCarl** [comment]
Either system-mqtt failed to detect these parts of your system or failed to register them with your Home Assistant.
Considering that CPU usage and Memory usage are working correctly, it's more likely system-mqtt failed to detect these parts of your system.

The best place to start would be the log file. Assuming you installed this as a Debian package and didn't modify the service file, you can run `journalctl -u system-mqtt.service -b` to see all logs since last boot.

Please post those logs.

**Comment by FrankTodoque** [comment]
The broker is running:

![Screenshot from 2023-05-05 16-36-44](https://user-images.githubusercontent.com/131161586/236488776-cf5dcef4-148a-4ef7-b4a2-8f3ddb6c6069.png)


The logfile has no entries:
```
~$ journalctl -u system-mqtt.service -b
-- Journal begins at Wed 2023-05-03 23:48:49 CEST, ends at Fri 2023-05-05 16:32:13 CEST. --
-- No entries --
```

**Comment by IamTheCarl** [comment]
Well that's peculiar. If you're getting data, system-mqtt should be running, and if it's running there should be at least a startup message in the log file.

Well let's get some details to try and clear this up. Sorry if some of these questions seem obvious but I don't want to overlook something simple before going down a rabbit hole.

First, if you rebooted the system since the last time system-mqtt ran, that `-b` option would have hidden it.
Try running `journalctl -u system-mqtt.service` and see what you get. If still nothing, then answer the following questions.

How did you go about installing system-mqtt?
How did you go about starting system-mqtt?

**Comment by FrankTodoque** [comment]
Now there is something in the log file:

`journalctl -u system-mqtt.service -b`
`Fatal error: Failed to get password from keyring. If you have not yet set the password, run system-mqtt set-password.`

Strange, because mqttuser is entered in HA, in the keyring and in the configuration file.

`my etc/system-mqtt.yaml:`

```
mqtt_server: mqtt://localhost
username: mqttuser
password_source: keyring
...
```

![Bildschirmfoto vom 2023-05-16 13-07-16](https://github.com/IamTheCarl/system-mqtt/assets/131161586/260437ed-bfae-492e-bc00-d9c7ba2f41b6)

**Comment by IamTheCarl** [comment]
That is quite peculiar. I wouldn't expect any sensors to work in this situation.

When you set the password, did you do it as root? It's been a long while since I implemented and tested that feature but I suspect root and your user account have separate keyrings.

**Comment by FrankTodoque** [comment]
No, I have assigned the password as a user.
Whatever strange error it may be - I give up.
Nevertheless, thanks for your efforts and best regards from Berlin.
